CREATE TABLE aluno(
  id SERIAL PRIMARY KEY,
  nome VARCHAR(20),
  idade INTEGER,
  email TEXT,
  senha TEXT
);

CREATE TABLE IF NOT EXISTS curso (
  id SERIAL PRIMARY KEY,
  nome TEXT NOT NULL
);

ALTER TABLE aluno
ADD COLUMN IF NOT EXISTS curso_id INTEGER,
ADD CONSTRAINT fk_curso FOREIGN KEY (curso_id) REFERENCES curso(id) ON DELETE SET NULL;

